version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:latest

    working_directory: ~/skybunk-server

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      
      - run: npm run-script code-format-check

      - run: npm test

      - run: npm run coverage

      - store_artifacts:
          path: coverage